name: ðŸš€ Update
on:
  push:
    branches:
      - development
  pull_request: {}

jobs:
    update:
        name: ðŸš€ Update
        runs-on: ubuntu-latest
        steps:
            - name: Check current directory
              run: |
                pwd
                ls -lah

            - name: ðŸ“‚ Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 50

            - name: ðŸ›  Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: ðŸ“¥ Download deps
              uses: bahmutov/npm-install@v1

            - name: ðŸš€ install tsx
              run: npm install tsx -G

            - name: Update DB
              run: npx tsx scripts/prebuild.ts
